version: "3"

name: defects4j

services:
  frontend:
    image: defects4j
    build:
      context:  ./Defects4j-FlaskApp
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always

