import pandas as pd
import jsoneditor as je
import os
import glob
import subprocess
import logging

from models import Tool
from flask.json import jsonify
from helpers import defects4j_helper as d4jh
from helpers import project_coverage_helper as pch
from helpers import csv_helper, file_paths

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

"""
This class represents a project in the analysis.
It is responsible for handling the project's data and running the analysis.

To create a new project, use projects/factory.py and inherit from this class.
"""
class Project:
    def __init__(self, name, version, tool):
        self.name = name
        self.version = version
        self.name_version = f"{name}-{version}"
        self.tool: Tool = tool
        self.available_versions = []

    def checkout_with_defects4j(self):
        d4jh.checkout_project(self.name, self.version)

    def compile_with_defects4j(self):
        d4jh.compile_project(self.name_version)

    def get_mutant_table_headers(self):
        return self.tool.get_mutant_table_headers()
    
    def get_project_total_mutants(self):
        if os.path.exists("/root/results.csv"):
            df = csv_helper.load_csv_from_root("results")
            return len(df)-1
    
        return 0
    
    def is_dev_suite_mutated(self):
        return os.path.exists("/root/" + self.name_version + "-" + self.tool.name + ".csv")
    
    def get_project_data(self):
        """
        Project data is cached after the first analysis.
        If the project data is cached, it is returned.
        Otherwise, the project data is fetched from the tools and the coverage data is generated.

        Returns:
            metric_data: The data related to the project's condition and line coverage.
            coverage_data: The color highlighting of the project's coverage.
        """
        project = self.name_version
        cached_project_data = je.read_imported_project_from_json(project)
        if cached_project_data and cached_project_data["metric_data"]:
            metric_data = cached_project_data["metric_data"]
            coverage_data = cached_project_data["coverage_data"]
        else:
            metric_data = d4jh.get_project_coverage(self.name_version)
            coverage_data = pch.get_line_coverage_color_highlighting(project)
            
            je.save_imported_project_in_json(self.name_version, metric_data, coverage_data)
        return metric_data, coverage_data

    def get_coverage(self):
        """
        Returns the coverage data of the project.
        The coverage data is generated by the tools and is cached in a json file.

        Returns:
            metric_data: The data related to the project's condition and line coverage.
            coverage_data: The color highlighting of the project's coverage.
        """
        project = self.name_version
        d4jh.set_test_suite_in_d4j_classpath(project)
        metric_data = d4jh.get_project_coverage(self.name_version)
        coverage_data = pch.get_line_coverage_color_highlighting(project)
            
        je.save_imported_project_in_json(self.name_version, metric_data, coverage_data)
        return metric_data, coverage_data

    def compile(self):
        project = self.name_version
        cmd = ("defects4j export -p cp.test -w $HOME/" + project + "f")
        output = subprocess.check_output(cmd, shell=True, text=True)

        cmd = ["javac", "-classpath", output, file_paths.student_test_file_path]

        process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE) 

        stdout, stderr = process.communicate()

        stdout = stdout.decode('utf-8')
        stderr = stderr.decode('utf-8')

        if process.returncode == 0:
            return jsonify({'message': "Compilation succeeded."})
        else:
            return jsonify({'message': "Compilation failed with return code: " + str(process.returncode) + "\n" + stderr})


    
    def clear_project_tools_output(self):
        """
        Clears the project's tools output directory.
        The directory is located at /root/{project}f/tools_output/{tool}/
        """
    
        path = '/root/' + self.name_version + 'f/tools_output/' + self.tool.name + '/*'
        files = glob.glob(path)

        for f in files:
            os.remove(f)

    def analyze_mutants(self, with_student_tests):
        project = self.name_version
        tool = self.tool.name

        self.clear_project_tools_output()

        try:
            d4jh.set_analysis_parameters(project, tool, with_student_tests)
            self.tool.run_analysis(project)
        except Exception as e:
            raise Exception(f"Error running analysis: {e}")

        csv_helper.store_project_specific_path_csv(project, tool)
        df1 = csv_helper.load_csv_from_root(project + "-" + tool)

        sheet_data = self.tool.get_mutant_table_data(df1, project)
        table_header = self.tool.get_mutant_table_headers()
        
        if os.path.exists("/root/results.csv"):
            df2 = csv_helper.load_csv_from_root("results")
            killed_list = self.get_project_mutant_killed_list_from_csvs(df1, df2)
            logger.info("killed_list: %s", killed_list)
        else:
            logger.info("BACKUP - Results file not found.")
            self.backup_generate()
            self.tool.run_analysis(project)
            df2 = csv_helper.load_csv_from_root("results")
            killed_list = self.get_project_mutant_killed_list_from_csvs(df1, df2)

        return sheet_data, table_header, killed_list

    def get_project_mutation_summary(self):
        project = self.name_version
        data = self.tool.get_mutation_summary(project)
        #total_mutants = self.get_cached_project_total_mutants()
        
        #logger.info("Total mutants 2: %s", total_mutants)
        logger.info("Data: %s", data)

        #killed_mutants = int(total_mutants) - int(data["Live mutants count"])
        #mutation_score = round(float(killed_mutants/int(total_mutants))*100,2)

        #logger.info("Killed mutants: %s", killed_mutants)
        #logger.info("Mutation score: %s", mutation_score)

        try:
            values = [data["Total mutants count"], data["Killed mutants count"], data["Live mutants count"], round(float(data["Mutation score"])*100,2)]
            return values
        except:
            raise Exception("KeyError: One or more keys not found in the data.")
        #values = [total_mutants, killed_mutants, data["Live mutants count"], mutation_score]

        return values

    def get_project_kill_matrix(self):
        return self.tool.get_kill_matrix(self.name_version)
    
    
    def get_project_mutant_killed_list_from_csvs(self, df1, df2):
        ids_df1 = set(df1['Mutant'])
        ids_df2 = set(df2['Mutant'])

        mutant_list = list(ids_df1 - ids_df2)

        return mutant_list

    def backup_generate(self):
        self.clear_project_tools_output()
        d4jh.set_analysis_parameters(self.name_version, self.tool.name, False)
    
    def get_devsuite_path(self):
        '''
        Fetches the dev suite tests related with the given project
        '''
        project = self.name_version
        path = "/root/" + project + "f"

        if not os.path.isdir(path):
            raise ValueError(f"The directory {path} does not exist.")
        
        cmd = "defects4j export -p dir.src.tests"

        result = subprocess.run(cmd, shell=True, cwd=path, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

        src = result.stdout

        cmd = "defects4j query -p " + self.name + " -q classes.relevant.test -o test.csv"
        result = subprocess.run(cmd, shell=True, cwd=path, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

        df = pd.read_csv("/root/" + project + "f/test.csv")
        value = df.isin([int(self.version)])
        row, _ = value.idxmax()
        bin = str(df.iat[row,1])

        bin = bin.replace('.', '/')

        return path + "/" + src + "/" + bin + ".java"

    def get_class_path(self):
        '''
        Fetches the class path of the project's buggy class
        '''
        project = self.name_version
        path = "/root/" + project + "f"
        if not os.path.isdir(path):
            raise ValueError(f"The directory {path} does not exist.")
        
        cmd = "defects4j export -p dir.src.classes"

        result = subprocess.run(cmd, shell=True, cwd=path, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

        src = result.stdout

        cmd = "defects4j export -p classes.modified"

        result = subprocess.run(cmd, shell=True, cwd=path, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

        bin = result.stdout

        bin = bin.replace('.', '/')

        return path + "/" + src + "/" + bin + ".java"